language: python

python:
  - "3.5"

sudo: required

env:
  global:
    - ANDROID_HOME=/opt/android-sdk-linux
    - PATH=$PATH:$ANDROID_HOME/tools
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - GRADLE_HOME=$HOME/gradle-cache

before_install:
  - "sudo apt-get install -y oracle-java8-set-default expect unzip lib32stdc++6 lib32z1"
  - "java -version"
  - "mkdir $HOME/gradle-cache"

install:
  - "make dependencies"

before_script:
  - "make install-sdks"

script:
  - "make test"
